#!/bin/bash

set -e

mkdir /etc/homeport
#mv /usr/share/homeport/configuration /etc/homeport/

#source /etc/homeport/configuration

#if [ -e /etc/os-release -a false ]; then
#    addgroup -S homeport && adduser -S homeport -G homeport
#else
    /usr/sbin/groupadd --gid 701 homeport
    /usr/sbin/useradd --shell /bin/bash --gid 701 --uid 701 homeport
#fi

cat /etc/passwd

mkdir -p /home/homeport
mkdir -p /var/run/sshd

echo "homeport ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ln -s /usr/share/homeport/container/docker.sh /usr/local/bin/docker

#sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
