#!/bin/bash

set -e

mkdir /etc/homeport
mv /usr/share/homeport/configuration /etc/homeport/

source /etc/homeport/configuration

/usr/sbin/groupadd --gid 701 homeport
/usr/sbin/useradd --gid 701 --uid 701 homeport

echo "homeport ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

mkdir -p /home/homeport
mkdir -p /var/run/sshd

ln -s /usr/share/homeport/container/docker.sh /usr/local/bin/docker

sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
