#!/bin/bash

set -e

mkdir -p /var/lib/homeport/appended/0

count=$(( $(ls /var/lib/homeport/appended | grep '^[0-9][0-9]*$' | sort -n | tail -n 1) + 1 ))

(cd /usr/share/homeport/append && bash invocation)

mv /usr/share/homeport/append /var/lib/homeport/appended/$count
