#!/bin/bash

login=$1

cat <<EOF > /etc/samba/smbusers
$login="$login"
EOF

cat <<EOF > /etc/samba/smb.conf
[global]
    workgroup = WORKGROUP
    server string = %h server (Samba, Ubuntu)
    dns proxy = no
    log file = /var/log/samba/log.%m
    max log size = 1000
    syslog = 0
    panic action = /usr/share/samba/panic-action %d
    server role = standalone server
    map to guest = bad user
    security = user
    username map = /etc/samba/smbusers
[Homeport]
    path = /home/$login
    browsable = yes
    writable = yes
    read only = no
    create mask = 0644
    directory mask = 2777
EOF

touch /etc/samba/password
chown 600 /etc/samba/password
ps ax | md5sum | cut -d' ' -f1 > /etc/samba/password
password=$(</etc/samba/password)

echo -ne "$password\n$password\n" | sudo smbpasswd -a -s $login

service smbd restart >/dev/null 2>/dev/null
