#!/bin/bash

declare -A exclude
IFS='=' read -ra excludes <<< "$1"
shift
for i in "${excludes[@]}"; do
    exclude[$i]=1
done

# We need to update the image so that the uid and gid of any files owned by the
# homeport user matches the uid and gid of the user running Homeport.
#
# This is an expensive, but not a lot of work. There are few if any files that
# belong to the homeport user outside of the mounted home directory.

# We `su` to the `homeport` user for OS X native Docker. The filesystem that
# mounts the host directory will report that the UID and GID of of the mounted
# files is that of the current user. We are currently root, but we need to be
# Homeport.
#
# Note that this means that we don't have to perform the search on OS X native.
home_uid=$(su homeport -c 'ls -ln /home/homeport/.homeport/touch' | awk '{ print $3 }')
home_gid=$(su homeport -c 'ls -ln /home/homeport/.homeport/touch' | awk '{ print $4 }')

homeport_uid_gid=$(awk -F ':' '$1 ~ "homeport" { print $3 ":" $4 }' /etc/passwd)

homeport_gid=${homeport_uid_gid#*:}
if [ "$home_gid" != "0" -a "$homeport_gid" != "$home_gid" ]; then
    group=$(awk -v gid=$home_gid -F ':' '$3 == gid { print $1 }' /etc/group)
    if [ ! -z "$group" ]; then
        next_gid=799
        found=yes
        while [ ! -z "$found" ]; do
            let next_gid=next_gid+1
            found=$(awk -v gid=$next_gid -F : '$3 == gid { print $1 }' /etc/group)
        done
        groupmod -g $next_gid $group
    fi
    groupmod -g $home_gid homeport
    find / -path /home/homeport -prune -o -group $homeport_gid -exec chgrp -h $home_gid {} \;
fi

homeport_uid=${homeport_uid_gid%:*}
if [ "$homeport_uid" != "$home_uid" ]; then
    user=$(awk -v uid=$home_uid -F ':' '$3 == uid { print $1 }' /etc/passwd)
    if [ ! -z "$user" ]; then
        next_uid=799
        found=yes
        while [ ! -z "$found" ]; do
            let next_uid=next_uid+1
            found=$(awk -v uid=$next_uid -F : '$3 == uid { print $1 }' /etc/passwd)
        done
        usermod -u $next_uid $user
    fi
    mkdir /tmp/home
    usermod -d /tmp/home homeport
    usermod -u $home_uid homeport
    usermod -d /home/homeport homeport
    rmdir /tmp/home
    find / -path /home/homeport -prune -o -user $homeport_uid -exec chown -h $home_uid {} \;
fi

while read -r line; do
    name=${line%%=*}
    if [ "${exclude[$name]}" != "1" ]; then
        echo $line
    fi
done < <(printenv | sort) >> /etc/environment

cat /etc/environment

if [ $# -ne 0 ]; then
    eval "$@"
fi

/usr/sbin/sshd -D -E /var/log/sshd.log
