#!/bin/bash

# Forgot what this was about??
declare -A exclude
IFS='=' read -ra excludes <<< "$1"
shift
for i in "${excludes[@]}"; do
    exclude[$i]=1
done

while read -r line; do
    name=${line%%=*}
    if [ "${exclude[$name]}" != "1" ]; then
        echo $line
    fi
done < <(printenv | sort) >> /etc/environment

cat /etc/environment

if [ $# -ne 0 ]; then
    eval "$@"
fi

ssh-keygen -A
/usr/sbin/sshd -D -E /var/log/sshd.log
