#!/bin/bash

declare -A exclude
IFS='=' read -ra excludes <<< "$1"
shift
for i in "${excludes[@]}"; do
    exclude[$i]=1
done

uid=$1
shift
gid=$1
shift

/etc/init.d/rsyslog start

while read -r line; do
    name=${line%%=*}
    if [ "${exclude[$name]}" != "1" ]; then
        echo $line
    fi
done < <(printenv | sort) >> /etc/environment

cat /etc/environment

if [ $# -ne 0 ]; then
    eval "$@"
fi

echo bindfs --map=$uid/homeport:@$gid/@homeport /var/lib/homeport/home /home/homeport
bindfs --map=$uid/homeport:@$gid/@homeport /var/lib/homeport/home /home/homeport
bindfs --map=$uid/homeport:@$gid/@homeport /var/lib/homeport/certs /home/homeport/.homeport/certs

/usr/sbin/sshd -D
