FROM ubuntu

MAINTAINER Alan Gutierrez, alan@prettyrobots.com

RUN apt-get update && apt-get -y upgrade && apt-get -y autoremove

RUN apt-get -y install curl libtool flex bison gcc make automake git
RUN apt-get -y install python
RUN apt-get -y install g++
RUN apt-get -y install build-essential
