FROM ubuntu
RUN apt-get update && apt-get -y upgrade && apt-get -y autoremove && apt-get -y install openssh-server bindfs sudo
COPY --from=homeport:homeport /usr/share/homeport/ /usr/share/homeport/
RUN find /usr/share/homeport/
RUN find /usr/share/homeport/container/foundation
RUN ls -la /usr/share/homeport/container/foundation
RUN printenv
RUN cat /etc/os-release
RUN /usr/share/homeport/container/foundation
EXPOSE 22
LABEL io.homeport true
