FROM ubuntu:bionic
RUN apt-get update && apt-get -y upgrade && apt-get -y autoremove && apt-get -y install openssh-server bindfs sudo
COPY --from=homeport/source /usr/share/homeport/ /usr/share/homeport/
RUN /usr/share/homeport/container/foundation
EXPOSE 22
LABEL io.homeport true
