#!/bin/bash

set -e


case "$OSTYPE" in
    darwin* )
        HOMEPORT_OS=OSX
        ;;
    linux* )
        HOMEPORT_OS=Linux
        ;;
    * )
        abend "Homeport will only run on OS X or Linux."
        ;;
esac

if [ "$1" == "module" ]; then
    echo $0
  echo "Please do not execute these programs directly. Use homeport."
  exit 1
fi

# At the top of every module. This will gather a usage message to share with the
# user if we abend.
function homeport() {
    [ "$1" == "module" ] || fail "invalid argument to homeport"
    local message; local spaces;
    IFS="\000" read -r -d'\000' message && true
    spaces=$(
        echo "$message" | sed -e '/^$/d' -e 's/^\( *\).*/\1/' | \
            sed -e '1h;H;g;s/[^\n]/#/g;s/\(#*\)\n\1/\n/;G;/^\n/s/\n.*\n\(.*\)\n.*/\1/;s/.*\n//;h;$!d'
    )
    USAGE="$(echo "$message" | sed -e "s/^$spaces//")"
}

function homeport_readlink() {
    file=$1
    if [ "$HOMEPORT_OS" = "OSX" ]; then
        if [ -L "$file" ]; then
            readlink $1
        else
            echo "$file"
        fi
    else
        readlink -f $1
    fi
}

function homeport_absolutize() {
    expanded=$(cd ${1/*} && homeport_readlink $1)
    readlink $1 1>&2
    echo x $expanded 1>&2
    base=${expanded##*/}
    dir=$(cd ${expanded%/*} && pwd -P)
    echo "$dir/$base"
}

function usage() {
  local code=$1
  echo "$USAGE"
  exit $code
}

function abend() {
  local message=$1
  echo "error: $message"
  usage 1
}

function homeport_exec() {
    local command=$1

    [ -z "$command" ] && abend "TODO: write usage"

    local action="$HOMEPORT_PATH/lib/$command"

    [ ! -e "$action"  ] && abend "invalid action: homeport $command"

    shift

    export HOMEPORT_PATH
    export -f usage abend getopt homeport

    "$action" $@
}

homeport_file=$0

while [ -L "$homeport_file" ]; do
    expanded=$(homeport_readlink "$homeport_file")
    pushd "${homeport_file%/*}" > /dev/null
    pushd "${expanded%/*}" > /dev/null
    HOMEPORT_PATH=$(pwd)
    popd > /dev/null
    popd > /dev/null
    homeport_file="$HOMEPORT_PATH/${homeport_file##*/}"
done

source "$HOMEPORT_PATH/getopt.bash"

homeport_exec $@
