#!/bin/bash

set -e

pushd $(dirname $0) > /dev/null
context=$(pwd -P)
popd > /dev/null
parent=$(dirname $context)

prefix="$parent"/build/usr/local
app="$parent"/node/app

docker run -it -v "$prefix":/usr/local:rw -v "$app":/app:ro bigeasy/gcc /app/compile
