#!/bin/bash

set -e

pushd $(dirname $0) > /dev/null
context=$(pwd -P)
popd > /dev/null
parent=$(dirname $context)

app="$parent"/node/app

usr_local_exists=$(echo $(                                                  \
    docker ps -a --no-trunc |                                               \
    awk 'NR > 1 && $(NF) ~ /^homeport_usr_local$/ {print $(NF)}' |          \
    wc -l                                                                   \
))

if [ "$usr_local_exists" = "0" ]; then
    docker run --name homeport_usr_local -v /usr/local -it bigeasy/gcc /bin/true
fi

docker run --rm -it --volumes-from homeport_usr_local -v "$app":/app:ro bigeasy/gcc /app/compile
