#!/bin/bash

set -e

homeport module <<-usage
    usage: homeport create --user [version] --account [Docker Hub account]

    description:

        Creates a configuration that stores the user name in a data container
        for use with all Homeport Create a configuration file in a volume named
        "/etc/data container named "homeport_configuration" for use with
        homeport.
usage

declare argv
argv=$(getopt -o u:h:a --long append,user:,hub: -- "$@") || return
eval "set -- $argv"

while true; do
    case "$1" in
        --user | -u)
            shift
            homeport_unix_user=$1
            shift
            ;;
        --append | -a)
            shift
            append=true
            ;;
        --hub | -h)
            shift
            homeport_docker_hub_account=$1
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

dir=$(mktemp -d -t homeport_nginx)

trap cleanup EXIT SIGTERM SIGINT

function cleanup() {
    local pids=$(jobs -pr)
    [ -n "$pids" ] && kill $pids
    rm -rf "$dir"
}

mkdir "$dir/src/" && \
    rsync -av "$HOMEPORT_PATH/" "$dir/src/" || abend "cannot create source archive"

while [ $# -ne 0 ]; do
    echo "0 $1" >> "$dir/src/packages"
    shift
done

cat "$dir/src/packages"

#docker run --name homeport_build_http -v "$dir":/usr/share/nginx/html:ro nginx

base=ubuntu

if [ "$append" -eq 1 ]; then
    base="$homeport_docker_hub_account/homeport_shell:latest"
fi

cat <<EOF > "$dir/Dockerfile"
FROM $base

MAINTAINER Alan Gutierrez, alan@prettyrobots.com

RUN apt-get update && apt-get -y upgrade && apt-get -y autoremove
COPY ./src/ /usr/share/homeport/
RUN /usr/share/homeport/container/install

EOF

docker build -t $homeport_docker_hub_account/homeport_shell:intermediate "$dir"

docker tag -f $homeport_docker_hub_account/homeport_shell:intermediate \
    $homeport_docker_hub_account/homeport_shell:latest
