#!/bin/bash

set -e

homeport module <<-usage
    usage: homeport create --user [version] --hub [Docker Hub account]

    description:

        Creates a configuration that stores the user name in a data container
        for use with all Homeport Create a configuration file in a volume named
        "/etc/data container named "homeport_configuration" for use with
        homeport.
usage

declare argv
argv=$(getopt -o u:h:a --long append,user:,hub: -- "$@") || return
eval "set -- $argv"

while true; do
    case "$1" in
        --user | -u)
            shift
            homeport_unix_user=$1
            shift
            ;;
        --hub | -h)
            shift
            homeport_docker_hub_account=$1
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

dir=$(mktemp -d -t homeport_nginx)

trap cleanup EXIT SIGTERM SIGINT

function cleanup() {
    local pids=$(jobs -pr)
    [ -n "$pids" ] && kill $pids
    rm -rf "$dir"
}

mkdir "$dir/src/" && \
    rsync -av "$HOMEPORT_PATH/" "$dir/src/" || abend "cannot create source archive"

cat <<EOF > "$dir/src/configuration"
homeport_unix_user=$homeport_unix_user
homeport_docker_hub_account=$homeport_docker_hub_account
EOF

cat "$dir/src/configuration"

cat <<EOF > "$dir/Dockerfile"
FROM ubuntu

MAINTAINER Alan Gutierrez, alan@prettyrobots.com

COPY ./src/ /usr/share/homeport/
RUN /usr/share/homeport/container/foundation
EOF

docker build -t $homeport_docker_hub_account/homeport_shell:foundation "$dir"
docker tag -f $homeport_docker_hub_account/homeport_shell:foundation \
    $homeport_docker_hub_account/homeport_shell:latest
docker tag -f $homeport_docker_hub_account/homeport_shell homeport_shell:$USER
