#!/bin/bash

set -e

homeport module <<-usage
    usage: homeport create --user [version] --account [Docker Hub account]

    description:

        Creates a configuration that stores the user name in a data container
        for use with all Homeport Create a configuration file in a volume named
        "/etc/data container named "homeport_configuration" for use with
        homeport.
usage

dir=$(mktemp -d -t homeport_nginx)

trap cleanup EXIT SIGTERM SIGINT

function cleanup() {
    local pids=$(jobs -pr)
    [ -n "$pids" ] && kill $pids
    rm -rf "$dir"
}

mkdir "$dir/src/" && \
    rsync -av "$HOMEPORT_PATH/" "$dir/src/" && \
    tar -C "$dir/src/" --exclude=./.git -czvf "$dir/homeport.tar.gz" "." && \
    rm -rf "$dir/src" || abend "cannot create source archive"

#docker run --name homeport_build_http -v "$dir":/usr/share/nginx/html:ro nginx

cat <<EOF > "$dir/Dockerfile"
FROM nginx

MAINTAINER Alan Gutierrez, alan@prettyrobots.com

COPY ./homeport.tar.gz /usr/share/nginx/html/
EOF

docker build -t bigeasy/homeport_build_nginx "$dir"

ip=$(boot2docker ip)

docker run --rm --name "homeport_build_nginx" -p 8080:80 bigeasy/homeport_build_nginx &

sleep 5

docker kill homeport_build_nginx > /dev/null
docker rmi bigeasy/homeport_build_nginx
