#!/bin/bash

set -e

homeport module <<-usage
    usage: homeport run
usage

trap cleanup EXIT SIGTERM SIGINT

function cleanup() {
    local pids=$(jobs -pr)
    [ -n "$pids" ] && kill $pids
}

launch='docker run '
launch+='--rm -it '
launch+='-u '$homeport_unix_user' '
launch+='--volumes-from '$homeport_home_volume' '
launch+='-v $(readlink -f $SSH_AUTH_SOCK):/home/'$homeport_unix_user/.ssh-agent' '
launch+='-e SSH_AUTH_SOCK=/home/'$homeport_unix_user'/.ssh-agent '
launch+='-h homeport '
launch+=$homeport_image_name' '

if [ $# -eq 0 ]; then
    launch+='/home/'$homeport_unix_user'/.homeportrc'
else
    launch+=$1
    shift
fi

if which boot2docker > /dev/null; then
    boot2docker ssh -At sh -c $(printf '%q' "$launch") "$@"
else
    $launch
fi
