#!/bin/bash

apt-get install -y make git automake libtool

mkdir /tmp/src && \
    git clone https://github.com/stedolan/jq.git /tmp/src/jq && \
    cd /tmp/src/jq && \
    git pull origin master && \
    autoreconf -i && \
    ./configure --prefix=/usr/local && \
    make install && \
    rm -rf /tmp/src
