#!/bin/bash

set -e

apt-get install -y samba

awk '/^exit$/ { p=1;next } { if (p) { print } }' $0 > /usr/local/bin/share

chmod 755 /usr/local/bin/share

exit
#!/bin/bash

ip=$1

login=$SUDO_USER

cat <<EOF > /etc/samba/smb.conf
[global]
    workgroup = WORKGROUP
    server string = %h server (Samba, Ubuntu)
    dns proxy = no
    log file = /var/log/samba/log.%m
    max log size = 1000
    syslog = 0
    panic action = /usr/share/samba/panic-action %d
    server role = standalone server
    map to guest = bad user
[Homeport]
    path = /home/$login
    browsable = yes
    writable = yes
    read only = no
    create mask = 0644
    directory mask = 2777
EOF

password=$(ps ax | md5sum | cut -d' ' -f1)
echo -ne "$password\n$password\n" | smbpasswd -a -s $login

service smbd restart >/dev/null 2>/dev/null

echo "cifs://$login:$password@$ip/Homeport"
