#!/bin/bash

set -e

url=$1
checksum=$2

apt-get install -y curl python make g++

mkdir /tmp/src
curl "$url" > /tmp/src/node.tar.gz

if [ $(sha256sum /tmp/src/node.tar.gz | cut -f1 -d' ') != "$checksum" ]; then
    echo "checksum $checksum invalid for $url" 1>&2
    exit 1
fi

cd /tmp/src
tar zxvf node.tar.gz
cd /tmp/src/node-*
pwd
./configure --prefix=/usr/local
make install
rm -rf /tmp/src
