#!/bin/bash

set -e

apt-get install -y netatalk avahi-daemon avahi-utils dbus

source /etc/homeport/configuration

password=$(ps ax | md5sum | cut -f1 -d' ')

sed -i.bak -e 's@/usr/bin/dbus-@/bin/dbus-@g' /etc/init.d/dbus
sed -i.bak -e 's@/usr/bin/dbus-@/bin/dbus-@g' /etc/default/netatalk

echo '- -tcp -noddp -uamlist uams_dhx.so,uams_dhx2.so -nosavepassword' >> /etc/netatalk/afpd.conf

echo "homeport":"$password" | chpasswd

mkdir -p /usr/local/bin
mkdir -p /usr/local/etc

cat <<EOF > /usr/local/bin/netatalk
#!/bin/bash

docker_host_address=\$1

/etc/init.d/dbus restart > /dev/null
/etc/init.d/avahi-daemon restart > /dev/null
/etc/init.d/netatalk restart > /dev/null

echo "afp://homeport:$password@\$docker_host_address" > /usr/local/etc/netatalk
EOF

chmod 755 /usr/local/bin/netatalk
